# `BERCHMANS KEVIN S`


## Department of Data Science - Data and Visual Analytics Lab


## `Red Wine Quality Data Analytics using NumPy Part-I`

In [1]:
'''
wine quality dataset 11 input features and 1 output feature 

1- fixed acidity
2- volatile acidity
3-citric acid
4-residual sugar
5-chlorides
6-free sulfurdioxide
7- total sulfur dioxide
8- density
9- pH
10- sulphates
11- alcohol output variable(based on sensory data): 
12- quality(score between 0 and 10)'''

'\nwine quality dataset 11 input features and 1 output feature \n\n1- fixed acidity\n2- volatile acidity\n3-citric acid\n4-residual sugar\n5-chlorides\n6-free sulfurdioxide\n7- total sulfur dioxide\n8- density\n9- pH\n10- sulphates\n11- alcohol output variable(based on sensory data): \n12- quality(score between 0 and 10)'

### import modules for numpy

In [2]:
import numpy as np

In [3]:
wines = np.genfromtxt("winequality-red.csv", delimiter=";", skip_header=1)

In [4]:
wines

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

#### What is its size?

In [5]:
np.shape(wines)

(1599, 12)

#### How many wine data rows here? 


In [6]:
np.shape(wines)[0]

1599

#### How many wine data columns here? 

In [7]:
np.shape(wines)[1]

12

#### How many dimensions? 

In [8]:
np.ndim(wines)

2

#### What is the type of wines? 


In [9]:
type(wines)

numpy.ndarray

#### What is the data type of wines data? 

In [10]:
wines.dtype

dtype('float64')

#### Show top 5 rows 

In [11]:
wines[:5]

array([[7.400e+00, 7.000e-01, 0.000e+00, 1.900e+00, 7.600e-02, 1.100e+01,
        3.400e+01, 9.978e-01, 3.510e+00, 5.600e-01, 9.400e+00, 5.000e+00],
       [7.800e+00, 8.800e-01, 0.000e+00, 2.600e+00, 9.800e-02, 2.500e+01,
        6.700e+01, 9.968e-01, 3.200e+00, 6.800e-01, 9.800e+00, 5.000e+00],
       [7.800e+00, 7.600e-01, 4.000e-02, 2.300e+00, 9.200e-02, 1.500e+01,
        5.400e+01, 9.970e-01, 3.260e+00, 6.500e-01, 9.800e+00, 5.000e+00],
       [1.120e+01, 2.800e-01, 5.600e-01, 1.900e+00, 7.500e-02, 1.700e+01,
        6.000e+01, 9.980e-01, 3.160e+00, 5.800e-01, 9.800e+00, 6.000e+00],
       [7.400e+00, 7.000e-01, 0.000e+00, 1.900e+00, 7.600e-02, 1.100e+01,
        3.400e+01, 9.978e-01, 3.510e+00, 5.600e-01, 9.400e+00, 5.000e+00]])

#### What is the value at 3rd row, 4th column of wine data? 

In [12]:
print(wines[2,3])

2.3


#### Select first 3 items in 4th column 

In [13]:
print(wines[:3,3])

[1.9 2.6 2.3]


#### Show 1st column 

In [14]:
wines[:,0]

array([7.4, 7.8, 7.8, ..., 6.3, 5.9, 6. ])

#### Show 2nd row 

In [15]:
wines[1]

array([ 7.8   ,  0.88  ,  0.    ,  2.6   ,  0.098 , 25.    , 67.    ,
        0.9968,  3.2   ,  0.68  ,  9.8   ,  5.    ])

#### Select items from rows 1 to 3 and 5th column 

In [16]:
print(wines[1:4,4])

[0.098 0.092 0.075]


#### Select entire array

In [17]:
wines[:]

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

#### Change 1st value in wines to 100 

In [18]:
wines[0,0]

7.4

In [19]:
wines[0,0] = 100

In [20]:
wines[0,0]

100.0

#### Change it back to 7.4 and print


In [21]:
a = wines[0,0] = 7.4

In [22]:
a

7.4

### 1-Dimensional Numpy Arrays

#### Select 4th row all column values

In [23]:
a = wines[3,:]

####  Display its values

In [24]:
print(a)

[11.2    0.28   0.56   1.9    0.075 17.    60.     0.998  3.16   0.58
  9.8    6.   ]


#### Show the 2 values

In [25]:
a[1]

0.28

#### int_array = float_array.astype(int)

In [26]:
a = wines.astype(int)

In [27]:
a

array([[ 7,  0,  0, ...,  0,  9,  5],
       [ 7,  0,  0, ...,  0,  9,  5],
       [ 7,  0,  0, ...,  0,  9,  5],
       ...,
       [ 6,  0,  0, ...,  0, 11,  6],
       [ 5,  0,  0, ...,  0, 10,  5],
       [ 6,  0,  0, ...,  0, 11,  6]])

### Vectorization Operations

#### Increase wine quality score (output variable) by 10 

In [28]:
wines[:,-1]

array([5., 5., 5., ..., 6., 5., 6.])

#### increase by 10

In [29]:
quality = wines[:,-1] + 10

#### Display update score

In [30]:
quality

array([15., 15., 15., ..., 16., 15., 16.])

#### Multiply alcohol of all wine data by 3 times

In [31]:
alcohol = wines[:,10] * 3

#### show updated alcohol column

In [32]:
alcohol

array([28.2, 29.4, 29.4, ..., 33. , 30.6, 33. ])

#### Add quality  column by  itself

#### wines[:,-1] + wines[:,-1] + 20

In [33]:
add = quality + quality

In [34]:
add

array([30., 30., 30., ..., 32., 30., 32.])

#### Multiply alcohol and wine quality columns. It will perform element wise multiplication 

In [35]:
multiply = alcohol * quality

In [36]:
multiply

array([423., 441., 441., ..., 528., 459., 528.])

## Broadcasting 


#### Add every row of wines data with a random array of values 


In [37]:
import numpy as np

In [38]:
rand_array = np.random.randn(1,12)

add = rand_array + wines

#### Show rand_array

In [39]:
rand_array

array([[-0.55211839, -0.82199209,  0.21799148, -0.96189119,  0.83505618,
         0.89556183, -1.1601269 ,  0.21673456, -0.32755911,  0.73512239,
        -1.77925252,  0.87893945]])

#### add wines and rand_array

In [40]:
add1 = wines + rand_array
add1

array([[ 6.84788161, -0.12199209,  0.21799148, ...,  1.29512239,
         7.62074748,  5.87893945],
       [ 7.24788161,  0.05800791,  0.21799148, ...,  1.41512239,
         8.02074748,  5.87893945],
       [ 7.24788161, -0.06199209,  0.25799148, ...,  1.38512239,
         8.02074748,  5.87893945],
       ...,
       [ 5.74788161, -0.31199209,  0.34799148, ...,  1.48512239,
         9.22074748,  6.87893945],
       [ 5.34788161, -0.17699209,  0.33799148, ...,  1.44512239,
         8.42074748,  5.87893945],
       [ 5.44788161, -0.51199209,  0.68799148, ...,  1.39512239,
         9.22074748,  6.87893945]])